export const data = [
  {
    no: 1,
    productid: 'a3KEeZbXBx',
    productname: 'Drinking Glass',
    amount: 10,
    time: '',
    company: 'Magic Box Asia ',
  },
  {
    no: 2,
    productid: 'xEBjTv2RhB',
    productname: 'Post it',
    amount: 20,
    time: '',
    company: 'Magic Box Asia',
  },
  {
    no: 3,
    productid: '7i8xzdx1OO',
    productname: 'Marker(Black color)',
    amount: 30,
    time: '',
    company: 'Magic Box Asia',
  },
  {
    no: 4,
    productid: '7YcgFL8zb9',
    productname: 'Paper(A4)',
    amount: 40,
    time: '',
    company: 'Magic Box Asia',
  },
  {
    no: 5,
    productid: 'XmUwfOCzKv',
    productname: 'Coffee maker',
    amount: 50,
    time: '',
    company: 'Magic Box Asia',
  },
  {
    no: 6,
    productid: 'Y3nSy3Wcsw',
    productname: 'U Beer',
    amount: 60,
    time: '',
    company: 'Magic Box Asia',
  },
  {
    no: 7,
    productid: 'WWcQZYpEEw',
    productname: 'Microwave',
    amount: 70,
    time: '',
    company: 'Magic Box Asia',
  },
  {
    no: 8,
    productid: 'BImPJwGAZE',
    productname: 'Ceramic Plate',
    amount: 80,
    time: '',
    company: 'Magic Box Asia',
  },
  {
    no: 9,
    productid: '4Eh8SiaaWK',
    productname: 'Curtain',
    amount: 90,
    time: '',
    company: 'Magic Box Asia',
  },
  {
    no: 10,
    productid: 'Db6yY11WIj',
    productname: 'Calendar',
    amount: 100,
    time: '',
    company: 'Magic Box Asia',
  },
]
